* libopenvas.pc.in: Raised glib dependency to 2.12.
* configure: Updated

* MANIFEST: Updated.

* CHANGES: Added draft text for 3.0.0-beta1 release.

* VERSION: Upgraded to 3.0.0.beta1.SVN



git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-libraries@5097 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19007,12 +19007,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GLIB_CFLAGS="$GLIB_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.6.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.6.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.12.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.12.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.6.0" 2>/dev/null`
+  pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.12.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -19025,12 +19025,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GLIB_LIBS="$GLIB_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.6.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.6.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.12.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.12.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.6.0" 2>/dev/null`
+  pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.12.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -19049,21 +19049,21 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glib-2.0 >= 2.6.0"`
+	        GLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glib-2.0 >= 2.12.0"`
         else
-	        GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0 >= 2.6.0"`
+	        GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0 >= 2.12.0"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GLIB_PKG_ERRORS" >&5
 
 	{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-                { { echo "$as_me:$LINENO: error: \"glib >= 2.6.0 not found\"" >&5
-echo "$as_me: error: \"glib >= 2.6.0 not found\"" >&2;}
+                { { echo "$as_me:$LINENO: error: \"glib >= 2.12.0 not found\"" >&5
+echo "$as_me: error: \"glib >= 2.12.0 not found\"" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
-	{ { echo "$as_me:$LINENO: error: \"glib >= 2.6.0 not found\"" >&5
-echo "$as_me: error: \"glib >= 2.6.0 not found\"" >&2;}
+	{ { echo "$as_me:$LINENO: error: \"glib >= 2.12.0 not found\"" >&5
+echo "$as_me: error: \"glib >= 2.12.0 not found\"" >&2;}
    { (exit 1); exit 1; }; }
 else
 	GLIB_CFLAGS=$pkg_cv_GLIB_CFLAGS
@@ -25281,7 +25281,7 @@ esac
 
 
 
-ac_config_files="$ac_config_files openvas-libraries.tmpl libopenvas-config include/libvers.h"
+ac_config_files="$ac_config_files openvas-libraries.tmpl libopenvas.pc libopenvas-config include/libvers.h"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -25838,6 +25838,7 @@ do
   case $ac_config_target in
     "include/config.h") CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
     "openvas-libraries.tmpl") CONFIG_FILES="$CONFIG_FILES openvas-libraries.tmpl" ;;
+    "libopenvas.pc") CONFIG_FILES="$CONFIG_FILES libopenvas.pc" ;;
     "libopenvas-config") CONFIG_FILES="$CONFIG_FILES libopenvas-config" ;;
     "include/libvers.h") CONFIG_FILES="$CONFIG_FILES include/libvers.h" ;;
 
